stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - data
    - data_load
    outs:
    - ${data.data_base_dir}/${data.dataset_name}/${data.annotations}

  build_embeddings:
    cmd: python src/stages/build_embeddings.py --config=params.yaml
    deps:
    - ${data.data_base_dir}/${data.dataset_name}/${data.annotations}
    params:
    - embeddings
    outs:
    - ${data.data_base_dir}/${data.dataset_name}/${data.embeddings_dir}/embeddings.parquet

  build_index:
    cmd: python src/stages/build_index.py --config=params.yaml
    deps:
    - src/stages/build_index.py
    - ${data.data_base_dir}/${data.dataset_name}/${data.embeddings_dir}/embeddings.parquet
    params:
    - build_index
    outs:
    - ${build_index.models_dir}/${build_index.model_name}:
        cache: false
    
  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - ${build_index.models_dir}/${build_index.model_name}
    - ${data.data_base_dir}/${data.dataset_name}/${data.embeddings_dir}/embeddings.parquet
    - src/stages/evaluate.py
    params:
    - evaluate
    metrics:
    - ${evaluate.reports_dir}/${evaluate.metrics_map5}:
        cache: false
    plots:
    - ${evaluate.reports_dir}/${evaluate.plots_metrics_all}:
        cache: false
    outs: 
    - ${evaluate.reports_dir}/${evaluate.metrics_all}:
        cache: false
