base:
  project: search_index

data:
  dataset_name: baseline_split
  data_base_dir: ../data
  embeddings_dir: embeddings
  embeddings: embeddings.parquet
  annotations: annotations.csv


  # Datasets
  baseline_split:
    name: baseline_split                  # name of the dataset and directory in 'data_dir' ->  '../data/baseline_split'
    data_dir: ../data                     # dir that contains data 
    data_subdir: test                     # subdir to use ->  '../data/baseline_split/test'
    is_zipped: true
    data_zip_filename: baseline_split.zip

  guie_custom_data_224:  # (TBD, not shared)
    name: guie_custom_data_224
    data_dir: ~/storage/kaggle-guie
    data_subdir: test

data_load:
  num_examples: 'all'                     # Set 'all' to use whole dataset

embeddings:
  batch_size: 2
  models_dir: models
  model_name: saved_model.pt

build_index:
  models_dir: models
  model_name: faiss.index
  
evaluate:
  reports_dir: reports
  metrics_map5: metrics_map5.json
  metrics_all: metrics_all.csv
  plots_metrics_all: plot_metrics_all.png
  query_results: query_results.csv
